refactor: refactored manager_tennis_scoreboard

diff --git a/manager_tennis_scoreboard b/manager_tennis_scoreboard
--- a/manager_tennis_scoreboard
+++ b/manager_tennis_scoreboard
@@ -1,5 +1,9 @@
 #!/bin/bash
 
+######################
+# deploy manager 1.0 #
+######################
+
 PROJECT_NAME="Tennis-Scoreboard"
 LOCAL_DIR=$(pwd)
 REPOSITORY_DIR=${LOCAL_DIR}/${PROJECT_NAME}
@@ -13,19 +17,19 @@ README_PATH="https://github.com/dDevusS/Tennis-Scoreboard"
 
 # Function for checking existing image and creating if not exist.
 init_image() {
-    if [[ -n $(docker images -q $DOCKER_IMAGE) ]]; then
-        echo "Docker image \"$DOCKER_IMAGE\" already exists."
+    if [[ -n $(docker images -q ${DOCKER_IMAGE}) ]]; then
+        echo "Docker image \"${DOCKER_IMAGE}\" already exists."
         exit 0
     else
-        echo "Docker image \"$DOCKER_IMAGE\" does not exist. Preparing to build the image..."
+        echo "Docker image \"${DOCKER_IMAGE}\" does not exist. Preparing to build the image..."
 
         if ! search_repository; then
           clone_repository
         fi
 
         echo "Building the image ..."
-        docker build -t $DOCKER_IMAGE ${REPOSITORY_DIR} || {
-          echo "Error: Failed to build Docker image. Please, look into README on $README_PATH";
+        docker build -t "${DOCKER_IMAGE}" "${REPOSITORY_DIR}" || {
+          echo "Error: Failed to build Docker image. Please, look into README on ${README_PATH}";
           exit 1;
           }
     fi
@@ -78,14 +82,14 @@ run_docker_container() {
     fi
 
     # Checking existing of the container and creating it, if not exist, then running the container.
-    if docker ps -a --format '{{.Names}}' | grep -Eq "^$CONTAINER_NAME$"; then
+    if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}$"; then
         echo "Container \"${CONTAINER_NAME}\" already exists. Restarting the container on port ${port}..."
         docker container stop ${CONTAINER_NAME}
         docker container rm ${CONTAINER_NAME}
     fi
 
     echo "Running Docker container on port $port..."
-    docker run -d -p "${port}":8080 --name ${CONTAINER_NAME} $DOCKER_IMAGE || {
+    docker run -d -p "${port}":8080 --name ${CONTAINER_NAME} ${DOCKER_IMAGE} || {
       echo "Error: Failed to start Docker container.";
       exit 1;
       }
@@ -108,10 +112,10 @@ clean() {
         "")
           delete_repository
           ;;
-        "--all")
+        --all)
           delete_all
           ;;
-        "--docker")
+        --docker)
           clean_docker
           ;;
         *)
@@ -126,13 +130,13 @@ delete_repository() {
     if search_repository; then
       if [[ $(pwd) == "${REPOSITORY_DIR}" ]]; then
         echo "Moving manager file ..."
-        cp -u $0 ..
+        cp -u "$0" ..
         cd ..
         echo "Deleting repository ..."
-        rm -rf ${REPOSITORY_DIR}
+        rm -rf "${REPOSITORY_DIR}"
       else
         echo "Deleting repository ..."
-        rm -rf ${REPOSITORY_DIR}
+        rm -rf "${REPOSITORY_DIR}"
       fi
       echo "Local repository ${REPOSITORY_DIR} was deleted."
     fi
@@ -144,7 +148,7 @@ delete_all() {
   delete_repository
 
     read -p "Are you sure you want to delete ${MANAGER_FILE} script? [y/N] " response
-    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
+    if [[ "${response}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
       rm "$0"
       echo "${MANAGER_FILE} has been deleted."
     else
@@ -158,7 +162,7 @@ delete_all() {
 clean_docker() {
   echo "Preparing to remove the container ..."
 
-  if docker ps -a --format '{{.Names}}' | grep -Eq "^$CONTAINER_NAME$"; then
+  if docker ps -a --format '{{.Names}}' | grep -Eq "^${CONTAINER_NAME}$"; then
     docker container stop ${CONTAINER_NAME}
     docker container rm ${CONTAINER_NAME}
     echo "The container has been deleted."
@@ -168,24 +172,24 @@ clean_docker() {
 
   echo "Preparing to remove the image ..."
 
-  if [[ -n $(docker images -q $DOCKER_IMAGE) ]]; then
+  if [[ -n $(docker images -q ${DOCKER_IMAGE}) ]]; then
     docker image rm -f ${DOCKER_IMAGE}
     echo "The image has been deleted."
   else
-    echo "Docker image \"$DOCKER_IMAGE\" does not exist."
+    echo "Docker image \"${DOCKER_IMAGE}\" does not exist."
   fi
 }
 
 # Function for getting help.
 show_help() {
-        if [ -z "$(docker images -q $DOCKER_IMAGE)" ]; then
+        if [ -z "$(docker images -q ${DOCKER_IMAGE})" ]; then
             echo "Usage: $0 {init|run [--port PORT_NUMBER]|stop|clean [--all|--docker]|--help}"
         else
             echo "Usage: $0 {run [--port PORT_NUMBER]|stop|clean [--all|--docker]|--help}"
         fi
 
     echo "Options:"
-        if [ -z "$(docker images -q $DOCKER_IMAGE)" ]; then
+        if [ -z "$(docker images -q ${DOCKER_IMAGE})" ]; then
             echo "  init        Clone repository and build Docker image"
         fi
     echo "  run            Run Docker container on default port (8080)"
@@ -199,19 +203,19 @@ show_help() {
 
 # Checking arguments
 case $1 in
-    "init")
+    init)
         init_image
         ;;
-    "run")
+    run)
         run_docker_container "$2" "$3"
         ;;
-    "stop")
+    stop)
         stop_docker_container
         ;;
-    "clean")
+    clean)
         clean "$2"
         ;;
-    "--help")
+    --help)
         show_help
         ;;
     *)
